kube-prometheus-stack:
  grafana:
    enabled: false
    forceDeployDatasources: true
    forceDeployDashboards: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
  prometheus:
    prometheusSpec:
      storageSpec: 
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false