external-dns:
  provider: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: api-token
  extraArgs:
    - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
    - --source=ingress # ingress is also possible
    - --domain-filter=vergl.cloud # (optional) limit to only example.com domains; change to match the zone created above.
    - --cloudflare-dns-records-per-page=5000 # (optional) configure how many DNS records to fetch per request