jackett:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: acme-issuer
      hajimari.io/appName: Jackett
      hajimari.io/icon: archive-search
    hosts:
      - host: &host jackett.vergl.cloud
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: jackett-tls-certificate
        hosts:
          - *host
  persistence:
    enabled: true