all:
  hosts:
    master1:
      ansible_host: 192.168.0.131
      ip: 192.168.0.131
      access_ip: 192.168.0.131
    master2:
      ansible_host: 192.168.0.132
      ip: 192.168.0.132
      access_ip: 192.168.0.132
    master3:
      ansible_host: 192.168.0.133
      ip: 192.168.0.133
      access_ip: 192.168.0.133
    worker1:
      ansible_host: 192.168.0.141
      ip: 192.168.0.141
      access_ip: 192.168.0.141
    worker2:
      ansible_host: 192.168.0.142
      ip: 192.168.0.142
      access_ip: 192.168.0.142
    worker3:
      ansible_host: 192.168.0.143
      ip: 192.168.0.143
      access_ip: 192.168.0.143
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    kube_node:
      hosts:
        worker1:
        worker2:
        worker3:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}