transmission:
  ingress:
    enabled: true
    hostname: &host transmission.vergl.cloud
    path: /
    pathType: ImplementationSpecific
    ingressClassName: nginx
  persistence:
    storageClassName: "longhorn"
    enabled: true
    accessModes: 
    - ReadWriteOnce
    size: 150Gi