apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAEU/MWEZM3qu+sO78RWy9w+IFglskvJtslUAmWFTvLqEidAHx0CD4FmprV28RpZyxqPlbWw0B6asTTWHMJTWBMpMS9PXnIWYrEhqeuzSsqFBlniStfWn0L5IiUS5YvDtly9FWm/C/ooW+EkAtnx+GN061dVAJQ51S8xMwLvQrTAyHYjq9K86679eGZ440TTNizqZtxSwGaarnFSOrqJzXx+AuaDX7NPRqleo9qo4is3AIftyO90lhqyYJrHfStrcWzucAKFqnnkFpNbCSj9VPkhHggOWaMBXipNjdvWnw4E1AOfCd3NZic0MzCB8hEl7nW/MYvqij6H9JXPsTbjlNgG1qbSAkg05YKQPLqLvMHzkB8VEpEwcww3V60D1l4KzDWhkM9iQUJZGoOuvyRgcDvfWBviS9hUDVjSDabE9+A1FX4T4LcwXPSWqZi2fJV5sHGg6jovFuZRyGbIzI9tNl5RShl87Pm0LcBF5Vss1BAiQjXzOhraflWzUYeoMXJHVZUKCMUFXbWvN6QZV2NrT7W6iZr8j7FCpLNx61ynTx9AZ/iU6fHO5VNjUc4YT/6yDRSW16g3QHQgQgjOLARAgq6q7M8zIzhhbl9mtfuT3kRN33nE/MDBqChRktGsOjOLzDw53nOvIM9b10ETubABouNQTO9kvr0CI9Iz/uYDUQDoND5bclIeWOsu5f4/aU1PHUqKXZSDt58DwKDh0VvKwIP7kct9avTDJ742+r0MpQWyAEE3tV/F7ry
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

